/* ── Assessment Questions Data ── */
export const assessmentData = {
  "climate-change-science-solutions": {
    title: "Climate Change: Science & Solutions",
    emoji: "🌍",
    headerBg: "#1A3D2B",
    questions: [
      {
        id: 1,
        question: "What is the primary greenhouse gas responsible for climate change?",
        options: [
          "Carbon Dioxide (CO₂)",
          "Nitrogen Oxide (N₂O)",
          "Methane (CH₄)",
          "Ozone (O₃)",
        ],
        correctAnswer: 0,
        explanation: "Carbon Dioxide is the primary greenhouse gas, accounting for about 75% of anthropogenic GHG emissions.",
      },
      {
        id: 2,
        question: "At what atmospheric CO₂ level were pre-industrial values?",
        options: [
          "350 ppm",
          "280 ppm",
          "450 ppm",
          "200 ppm",
        ],
        correctAnswer: 1,
        explanation: "Pre-industrial CO₂ levels were approximately 280 ppm. Current levels exceed 420 ppm.",
      },
      {
        id: 3,
        question: "What is a tipping point in the climate system?",
        options: [
          "A minor climate fluctuation",
          "A critical threshold beyond which a system reorganizes abruptly",
          "The highest temperature recorded annually",
          "An agreement between countries on climate action",
        ],
        correctAnswer: 1,
        explanation: "A tipping point is a critical threshold beyond which a climate system or subsystem reorganizes abruptly and irreversibly.",
      },
      {
        id: 4,
        question: "Which of the following is an example of climate mitigation?",
        options: [
          "Building seawalls to protect coastal areas",
          "Planting drought-resistant crops",
          "Transitioning to renewable energy",
          "Improving water infrastructure",
        ],
        correctAnswer: 2,
        explanation: "Mitigation reduces the causes of climate change (GHG emissions), while adaptation addresses impacts. Renewable energy is mitigation.",
      },
      {
        id: 5,
        question: "What does the Paris Agreement aim to limit global warming to?",
        options: [
          "2°C above pre-industrial levels",
          "1.5°C to 2°C above pre-industrial levels",
          "3°C above pre-industrial levels",
          "1°C above pre-industrial levels",
        ],
        correctAnswer: 1,
        explanation: "The Paris Agreement aims to limit global warming to well below 2°C, preferably to 1.5°C above pre-industrial levels.",
      },
      {
        id: 6,
        question: "Which gas has the highest warming potential per molecule?",
        options: [
          "Carbon Dioxide",
          "Methane",
          "Sulfur Hexafluoride",
          "Nitrous Oxide",
        ],
        correctAnswer: 2,
        explanation: "Sulfur Hexafluoride (SF₆) has an extremely high Global Warming Potential (23,500x that of CO₂).",
      },
      {
        id: 7,
        question: "What percentage of greenhouse gas emissions come from energy use?",
        options: [
          "25%",
          "50%",
          "65%",
          "85%",
        ],
        correctAnswer: 2,
        explanation: "Energy (electricity, heat, transport) accounts for approximately 65% of total global GHG emissions.",
      },
      {
        id: 8,
        question: "Which sector produces the most methane emissions?",
        options: [
          "Manufacturing",
          "Agriculture",
          "Waste",
          "Energy",
        ],
        correctAnswer: 1,
        explanation: "Agriculture (particularly livestock farming) is the largest source of methane emissions globally.",
      },
      {
        id: 9,
        question: "What is the role of the IPCC?",
        options: [
          "Enforce climate regulations",
          "Assess scientific knowledge on climate change",
          "Fund renewable energy projects",
          "Negotiate international climate agreements",
        ],
        correctAnswer: 1,
        explanation: "The IPCC (Intergovernmental Panel on Climate Change) assesses scientific, technical, and socio-economic information relevant to climate change.",
      },
      {
        id: 10,
        question: "Which renewable energy source is most abundant globally?",
        options: [
          "Solar",
          "Wind",
          "Hydropower",
          "Geothermal",
        ],
        correctAnswer: 0,
        explanation: "Solar energy has the largest theoretical potential to meet global energy demand.",
      },
      {
        id: 11,
        question: "What is the greenhouse effect?",
        options: [
          "The temperature inside a greenhouse",
          "The trapping of heat in the atmosphere by gases",
          "A method for growing crops",
          "The annual temperature increase in cities",
        ],
        correctAnswer: 1,
        explanation: "The greenhouse effect is the process where gases trap heat in the atmosphere, similar to how a greenhouse traps heat with its glass.",
      },
      {
        id: 12,
        question: "Which of these is NOT a climate feedback mechanism?",
        options: [
          "Ice-albedo feedback",
          "Water vapor feedback",
          "Cloud feedback",
          "Fossil fuel feedback",
        ],
        correctAnswer: 3,
        explanation: "Fossil fuel feedback is not a recognized climate feedback mechanism. The others are all documented positive feedbacks.",
      },
      {
        id: 13,
        question: "What is carbon sequestration?",
        options: [
          "Breaking down carbon molecules",
          "Capturing and storing carbon dioxide",
          "Burning organic matter",
          "Removing nitrogen from the atmosphere",
        ],
        correctAnswer: 1,
        explanation: "Carbon sequestration is the process of capturing and storing atmospheric CO₂ through natural or technological means.",
      },
      {
        id: 14,
        question: "Which activity has the largest carbon footprint per person?",
        options: [
          "Diet",
          "Transportation",
          "Home heating/cooling",
          "Electricity consumption",
        ],
        correctAnswer: 2,
        explanation: "Home heating and cooling (space conditioning) typically represents the largest portion of household carbon emissions.",
      },
      {
        id: 15,
        question: "What does NDC stand for?",
        options: [
          "National Development Code",
          "Nationally Determined Contribution",
          "Natural Disaster Coverage",
          "Nuclear Diversity Commission",
        ],
        correctAnswer: 1,
        explanation: "NDCs (Nationally Determined Contributions) are climate action plans submitted by countries under the Paris Agreement.",
      },
      {
        id: 16,
        question: "Which climate model is used by the IPCC for projections?",
        options: [
          "Coupled General Circulation Models (GCMs)",
          "Simple Linear Models",
          "Empirical Statistical Models",
          "Historical Trend Models",
        ],
        correctAnswer: 0,
        explanation: "The IPCC uses Coupled General Circulation Models (GCMs) and Earth System Models for climate projections.",
      },
      {
        id: 17,
        question: "What is ocean acidification?",
        options: [
          "The cooling of ocean water",
          "Increased pH levels in the ocean",
          "Decreased pH in oceans due to CO₂ absorption",
          "The addition of acids to the ocean",
        ],
        correctAnswer: 2,
        explanation: "Ocean acidification occurs when the ocean absorbs CO₂ from the atmosphere, forming carbonic acid and lowering pH.",
      },
      {
        id: 18,
        question: "Which country has set a net-zero target for 2050?",
        options: [
          "China only",
          "USA only",
          "Multiple countries including EU, UK, Japan",
          "No countries yet",
        ],
        correctAnswer: 2,
        explanation: "Multiple countries, including EU member states, UK, Japan, and others, have committed to net-zero by 2050.",
      },
      {
        id: 19,
        question: "What is the albedo effect?",
        options: [
          "The reflection of sunlight back to space",
          "The absorption of heat in the ocean",
          "The rotation of the Earth",
          "The movement of tectonic plates",
        ],
        correctAnswer: 0,
        explanation: "Albedo refers to the reflectivity of a surface. Ice has high albedo; melting ice reduces reflection, amplifying warming.",
      },
      {
        id: 20,
        question: "Which sector requires the most significant transformation for climate goals?",
        options: [
          "Agriculture",
          "Waste management",
          "Energy systems",
          "Construction",
        ],
        correctAnswer: 2,
        explanation: "Energy systems (power generation, heating, transport) require the most comprehensive transformation to achieve climate goals.",
      },
    ],
  },
  "carbon-accounting-reporting": {
    title: "Carbon Accounting & Reporting",
    emoji: "📊",
    headerBg: "#1B3A5C",
    questions: [
      {
        id: 1,
        question: "What does Scope 1 emissions refer to?",
        options: [
          "Purchased electricity",
          "Direct emissions from company-owned sources",
          "Emissions from supply chain",
          "Employee commuting",
        ],
        correctAnswer: 1,
        explanation: "Scope 1 covers direct GHG emissions from sources owned or controlled by the organization.",
      },
      {
        id: 2,
        question: "Which of the following is an example of Scope 2 emissions?",
        options: [
          "Fuel combustion in company vehicles",
          "Purchased electricity for office buildings",
          "Supplier manufacturing emissions",
          "Employee business travel",
        ],
        correctAnswer: 1,
        explanation: "Scope 2 includes emissions from purchased electricity, steam, heating, and cooling.",
      },
      {
        id: 3,
        question: "What is the primary framework for carbon accounting?",
        options: [
          "ISO 9001",
          "GHG Protocol Corporate Standard",
          "IFRS Standards",
          "SOX Compliance",
        ],
        correctAnswer: 1,
        explanation: "The GHG Protocol Corporate Standard is the most widely used framework for measuring and reporting corporate GHG emissions.",
      },
      {
        id: 4,
        question: "Which is NOT included in Scope 3 emissions?",
        options: [
          "Supplier emissions",
          "Employee commuting",
          "Facility heating",
          "Waste disposal",
        ],
        correctAnswer: 2,
        explanation: "Facility heating would be Scope 2 (purchased energy). Scope 3 covers value chain emissions.",
      },
      {
        id: 5,
        question: "What is an organizational boundary?",
        options: [
          "The physical location of the company",
          "The geographic area covered by operations",
          "The definition of which entities to include in emissions inventory",
          "The year-end cutoff for reporting",
        ],
        correctAnswer: 2,
        explanation: "Organizational boundaries define which legal entities, subsidiaries, and operations are included in the carbon inventory.",
      },
      {
        id: 6,
        question: "What does the GRI stand for?",
        options: [
          "Global Reporting Initiative",
          "Greenhouse Reporting Index",
          "Green Resource Institute",
          "Global Risk Inventory",
        ],
        correctAnswer: 0,
        explanation: "GRI (Global Reporting Initiative) provides standards for sustainability reporting including emissions.",
      },
      {
        id: 7,
        question: "Which approach assigns emissions to the entity with operational control?",
        options: [
          "Equity share approach",
          "Financial control approach",
          "Operational control approach",
          "Legal entity approach",
        ],
        correctAnswer: 2,
        explanation: "The operational control approach allocates emissions based on operational responsibility regardless of ownership percentage.",
      },
      {
        id: 8,
        question: "What is materiality in the context of sustainability reporting?",
        options: [
          "The physical substance of products",
          "Issues significant to business operations and stakeholders",
          "The size of the company",
          "The cost of compliance",
        ],
        correctAnswer: 1,
        explanation: "Materiality identifies sustainability issues that significantly affect business and are of concern to stakeholders.",
      },
      {
        id: 9,
        question: "What is carbon intensity?",
        options: [
          "The concentration of carbon in air",
          "Emissions per unit of output or activity",
          "The strength of carbon dioxide",
          "The color intensity of carbon",
        ],
        correctAnswer: 1,
        explanation: "Carbon intensity measures emissions relative to output (e.g., CO₂ per unit produced or per dollar revenue).",
      },
      {
        id: 10,
        question: "Which verification standard is most common for carbon accounting?",
        options: [
          "ISO 9001",
          "ISO 14064-1 and ISO 14065",
          "ISO 50001",
          "ISO 26000",
        ],
        correctAnswer: 1,
        explanation: "ISO 14064 series covers GHG quantification, monitoring, reporting, and ISO 14065 covers verification bodies.",
      },
      {
        id: 11,
        question: "What is activity data in emissions calculations?",
        options: [
          "Information about marketing activities",
          "Data on operational activities that generate emissions",
          "Social media engagement metrics",
          "Employee activity logs",
        ],
        correctAnswer: 1,
        explanation: "Activity data quantifies the extent of activities that generate emissions (e.g., fuel consumption, electricity use).",
      },
      {
        id: 12,
        question: "What is an emission factor?",
        options: [
          "A multiplier for increasing emissions",
          "The rate at which emissions decay",
          "A coefficient relating activity data to GHG emissions",
          "The percentage of total emissions",
        ],
        correctAnswer: 2,
        explanation: "An emission factor converts activity data into GHG emissions (e.g., kg CO₂ per kWh of electricity).",
      },
      {
        id: 13,
        question: "Which standard requires third-party verification?",
        options: [
          "GRI Standards (optional)",
          "Science-Based Targets initiative",
          "EU Emissions Trading Scheme (mandatory)",
          "Internal carbon accounting",
        ],
        correctAnswer: 2,
        explanation: "The EU ETS mandates third-party verification of emissions, while others typically offer optional verification.",
      },
      {
        id: 14,
        question: "What is a carbon offset?",
        options: [
          "A reduction in emissions",
          "A credit representing one ton of CO₂ equivalent reduction",
          "A government subsidy",
          "A tax deduction",
        ],
        correctAnswer: 1,
        explanation: "A carbon offset is a credit representing one metric ton of CO₂ equivalent emission reductions or removals.",
      },
      {
        id: 15,
        question: "How often should emissions be reported?",
        options: [
          "Every 5 years",
          "Annually (for most standards)",
          "Every 3 years",
          "On-demand",
        ],
        correctAnswer: 1,
        explanation: "Most reporting standards require annual emissions reporting and transparent tracking of progress.",
      },
      {
        id: 16,
        question: "What does RE100 commitment require?",
        options: [
          "Zero emissions",
          "100% renewable electricity",
          "Complete supply chain transparency",
          "Net-zero by 2050",
        ],
        correctAnswer: 1,
        explanation: "RE100 is a global initiative where companies commit to 100% renewable electricity.",
      },
      {
        id: 17,
        question: "Which organization publishes the GHG Protocol?",
        options: [
          "World Bank",
          "WRI and WBCSD",
          "UN Environment Programme",
          "International Energy Agency",
        ],
        correctAnswer: 1,
        explanation: "The GHG Protocol is published by the World Resources Institute (WRI) and World Business Council for Sustainable Development (WBCSD).",
      },
      {
        id: 18,
        question: "What is the primary benefit of carbon accounting?",
        options: [
          "Reducing government taxes",
          "Understanding and managing emissions",
          "Improving product packaging",
          "Reducing workforce",
        ],
        correctAnswer: 1,
        explanation: "Carbon accounting enables organizations to understand their emissions and identify reduction opportunities.",
      },
      {
        id: 19,
        question: "How many primary GHG gases does the Kyoto Protocol identify?",
        options: [
          "4",
          "6",
          "8",
          "10",
        ],
        correctAnswer: 1,
        explanation: "The Kyoto Protocol covers six GHGs: CO₂, CH₄, N₂O, HFCs, PFCs, and SF₆.",
      },
      {
        id: 20,
        question: "What is a carbon budget?",
        options: [
          "The financial cost of emissions",
          "The maximum allowable emissions for a period",
          "The investment in green technology",
          "The revenue from carbon offsets",
        ],
        correctAnswer: 1,
        explanation: "A carbon budget is the total amount of GHG emissions an organization can produce while meeting climate goals.",
      },
    ],
  },
  "ghg-accounting-protocol": {
    title: "GHG Accounting & the GHG Protocol",
    emoji: "🏭",
    headerBg: "#4A3800",
    questions: [
      {
        id: 1,
        question: "What is the primary focus of the GHG Protocol?",
        options: [
          "Environmental policy",
          "Standardized GHG accounting and reporting",
          "Renewable energy promotion",
          "Carbon offset trading",
        ],
        correctAnswer: 1,
        explanation: "The GHG Protocol provides standards for measuring and reporting greenhouse gas emissions.",
      },
      {
        id: 2,
        question: "Which GHG does the Protocol prioritize?",
        options: [
          "Only CO₂",
          "Six major greenhouse gases",
          "Methane only",
          "Nitrogen oxides",
        ],
        correctAnswer: 1,
        explanation: "The GHG Protocol covers all six major greenhouse gases for comprehensive emissions accounting.",
      },
      {
        id: 3,
        question: "What is the foundation of GHG Protocol calculations?",
        options: [
          "Historical trends",
          "Activity data × Emission factors",
          "Government estimates",
          "Industry averages",
        ],
        correctAnswer: 1,
        explanation: "The GHG Protocol uses the formula: Activity Data multiplied by Emission Factors to calculate emissions.",
      },
      {
        id: 4,
        question: "How many scopes are defined in the GHG Protocol?",
        options: [
          "2",
          "3",
          "4",
          "5",
        ],
        correctAnswer: 1,
        explanation: "The GHG Protocol defines three scopes of emissions: Scope 1, Scope 2, and Scope 3.",
      },
      {
        id: 5,
        question: "What year was the GHG Protocol Corporate Standard released?",
        options: [
          "1998",
          "2001",
          "2004",
          "2008",
        ],
        correctAnswer: 1,
        explanation: "The GHG Protocol Corporate Standard was first published in 2001.",
      },
      {
        id: 6,
        question: "Which IPCC category relates to energy?",
        options: [
          "Category 1",
          "Category 2",
          "Category 3",
          "Category 4",
        ],
        correctAnswer: 0,
        explanation: "IPCC Category 1 (Energy) is fundamental to GHG Protocol accounting.",
      },
      {
        id: 7,
        question: "What does GWP stand for?",
        options: [
          "Greenhouse Warming Potential",
          "Global Warming Potential",
          "Gas Warming Parameters",
          "Gross Warming Protocol",
        ],
        correctAnswer: 1,
        explanation: "GWP (Global Warming Potential) is used to compare the climate impact of different gases.",
      },
      {
        id: 8,
        question: "How is methane's GWP compared to CO₂?",
        options: [
          "Same as CO₂",
          "25-28 times higher",
          "5 times higher",
          "2 times higher",
        ],
        correctAnswer: 1,
        explanation: "Methane has a GWP of 25-28 times that of CO₂ over a 100-year period.",
      },
      {
        id: 9,
        question: "What is Scope 1 under the GHG Protocol?",
        options: [
          "Purchased electricity",
          "Direct emissions",
          "Business travel",
          "Supplier emissions",
        ],
        correctAnswer: 1,
        explanation: "Scope 1 includes direct emissions from sources owned or controlled by the organization.",
      },
      {
        id: 10,
        question: "What is Scope 2 under the GHG Protocol?",
        options: [
          "Direct emissions",
          "Purchased electricity and steam",
          "Supply chain emissions",
          "Employee commuting",
        ],
        correctAnswer: 1,
        explanation: "Scope 2 covers indirect emissions from purchased electricity, steam, heating, and cooling.",
      },
      {
        id: 11,
        question: "Which approach does the Protocol recommend for organizational boundaries?",
        options: [
          "Equity share only",
          "Financial control only",
          "Operational control only",
          "Organization can choose appropriate approach",
        ],
        correctAnswer: 3,
        explanation: "The GHG Protocol allows organizations to choose between equity share, financial control, or operational control.",
      },
      {
        id: 12,
        question: "What is the most common organizational boundary approach?",
        options: [
          "Equity share",
          "Financial control",
          "Operational control",
          "Legal entity",
        ],
        correctAnswer: 2,
        explanation: "Operational control is the most commonly used approach in the GHG Protocol.",
      },
      {
        id: 13,
        question: "How should companies handle equity investments under the Protocol?",
        options: [
          "Include all investments",
          "Exclude all investments",
          "Use equity share approach",
          "Use market value",
        ],
        correctAnswer: 2,
        explanation: "Equity share approach allocates emissions proportional to the percentage stake in the company.",
      },
      {
        id: 14,
        question: "What is a major challenge in Scope 3 accounting?",
        options: [
          "Lack of data availability",
          "Complexity and scope",
          "High verification costs",
          "Technical limitations",
        ],
        correctAnswer: 1,
        explanation: "Scope 3 is challenging due to its broad scope and the complexity of supply chain emissions.",
      },
      {
        id: 15,
        question: "How many Scope 3 categories exist in the GHG Protocol?",
        options: [
          "5",
          "10",
          "15",
          "20",
        ],
        correctAnswer: 2,
        explanation: "The GHG Protocol defines 15 categories of Scope 3 emissions.",
      },
      {
        id: 16,
        question: "What should be included in upstream Scope 3?",
        options: [
          "Retail sales",
          "Purchased goods and services",
          "Product use",
          "End-of-life treatment",
        ],
        correctAnswer: 1,
        explanation: "Upstream Scope 3 includes purchased goods and services from the supply chain.",
      },
      {
        id: 17,
        question: "What is downstream Scope 3?",
        options: [
          "Supplier emissions",
          "Manufacturing emissions",
          "Distribution and use phase emissions",
          "Direct facility emissions",
        ],
        correctAnswer: 2,
        explanation: "Downstream Scope 3 includes distribution, product use, and end-of-life treatment.",
      },
      {
        id: 18,
        question: "How frequently should GHG inventories be updated?",
        options: [
          "Every 5 years",
          "Every 3 years",
          "Annually",
          "As needed",
        ],
        correctAnswer: 2,
        explanation: "The GHG Protocol recommends annual GHG inventory updates and reporting.",
      },
      {
        id: 19,
        question: "What is a base year in GHG Protocol?",
        options: [
          "The current year",
          "A historical reference year for tracking progress",
          "The most recent year",
          "An average year",
        ],
        correctAnswer: 1,
        explanation: "A base year is a historical reference year used to track emissions reduction progress.",
      },
      {
        id: 20,
        question: "What should accompany GHG emissions data according to the Protocol?",
        options: [
          "Financial data only",
          "Uncertainty assessment and methodology documentation",
          "Marketing materials",
          "Historical trends",
        ],
        correctAnswer: 1,
        explanation: "The Protocol requires uncertainty assessment and clear methodology documentation with emissions data.",
      },
    ],
  },
  "life-cycle-assessment": {
    title: "Life Cycle Assessment (LCA)",
    emoji: "♻️",
    headerBg: "#3B1F72",
    questions: [
      {
        id: 1,
        question: "Which ISO standard defines the principles and framework of LCA?",
        options: ["ISO 14001", "ISO 14040", "ISO 14064", "ISO 50001"],
        correctAnswer: 1,
        explanation: "ISO 14040 describes the principles and framework for life cycle assessment (LCA).",
      },
      {
        id: 2,
        question: "The functional unit in an LCA is:",
        options: [
          "The unit of energy measurement in the system",
          "A quantified measure of the product system's function used as reference basis",
          "The geographic boundary of the LCA study",
          "The unit cost of a product across its life cycle",
        ],
        correctAnswer: 1,
        explanation: "The functional unit defines the quantification of identified functions of the product system.",
      },
      {
        id: 3,
        question: "Which LCA phase involves compiling inventory of all inputs and outputs?",
        options: [
          "Goal and Scope Definition",
          "Life Cycle Inventory (LCI) Analysis",
          "Life Cycle Impact Assessment (LCIA)",
          "Interpretation",
        ],
        correctAnswer: 1,
        explanation: "The Life Cycle Inventory (LCI) phase involves data collection and calculation procedures to quantify inputs and outputs.",
      },
      {
        id: 4,
        question: "The cradle-to-gate system boundary covers?",
        options: [
          "Raw material extraction through to end-of-life",
          "Raw material extraction through to the factory gate",
          "Manufacturing through to consumer use",
          "Consumer use through to end-of-life",
        ],
        correctAnswer: 1,
        explanation: "Cradle-to-gate covers raw material extraction through to the point where it leaves the factory.",
      },
      {
        id: 5,
        question: "What is LCIA in the context of LCA?",
        options: [
          "Life Cycle Inventory Analysis",
          "Life Cycle Impact Assessment",
          "Life Cycle Integrated approach",
          "Life Cycle International Authority",
        ],
        correctAnswer: 1,
        explanation: "LCIA is the Life Cycle Impact Assessment phase where inventory data is translated into potential environmental impacts.",
      },
      {
        id: 6,
        question: "A 'system boundary' in LCA determines:",
        options: [
          "The cost limit of the study",
          "Which processes are included or excluded from the study",
          "The maximum emissions allowed",
          "The duration of the product's life",
        ],
        correctAnswer: 1,
        explanation: "System boundaries define the scope of the LCA by identifying which life cycle stages and unit processes are included.",
      },
      {
        id: 7,
        question: "Impact categories in an LCA typically include:",
        options: [
          "Profitability and market share",
          "Global warming potential, acidification, and eutrophication",
          "Employee satisfaction and turnover",
          "Customer acquisition cost",
        ],
        correctAnswer: 1,
        explanation: "LCA evaluates environmental impacts like global warming, acidification, and eutrophication.",
      },
      {
        id: 8,
        question: "In LCA, 'normalization' is the process of:",
        options: [
          "Making the data look more professional",
          "Relating impact results to a reference value (e.g., total impacts of a region)",
          "Removing outliers from the inventory data",
          "Adjusting the product's price for inflation",
        ],
        correctAnswer: 1,
        explanation: "Normalization helps understand the relative magnitude of each impact category by comparing it to a reference.",
      },
      {
        id: 9,
        question: "Which of these is a 'cradle-to-grave' boundary?",
        options: [
          "Extraction to Manufacturing",
          "Extraction to End-of-Life (Disposal/Recycling)",
          "Manufacturing to Distribution",
          "Use phase only",
        ],
        correctAnswer: 1,
        explanation: "Cradle-to-grave covers the entire life cycle from raw material extraction to final disposal.",
      },
      {
        id: 10,
        question: "Allocation in LCA is needed when:",
        options: [
          "Budgeting for the project",
          "A process has more than one product (co-products)",
          "Hiring new consultants",
          "Selecting a functional unit",
        ],
        correctAnswer: 1,
        explanation: "Allocation is the process of partitioning the input or output flows of a process to the product system under study.",
      },
      {
        id: 11,
        question: "ISO 14044 focus on:",
        options: [
          "Management systems",
          "Requirements and guidelines for LCA",
          "Carbon footprinting only",
          "Corporate social responsibility",
        ],
        correctAnswer: 1,
        explanation: "ISO 14044 specifies requirements and provides guidelines for life cycle assessment (LCA).",
      },
      {
        id: 12,
        question: "Which is a 'primary' data source in LCA?",
        options: [
          "Industry average databases (e.g., Ecoinvent)",
          "Direct measurements from the specific manufacturing site",
          "Peer-reviewed literature",
          "Government statistical reports",
        ],
        correctAnswer: 1,
        explanation: "Primary data is collected directly from the specific processes within the system boundary.",
      },
      {
        id: 13,
        question: "Characterization factors are used to:",
        options: [
          "Describe the brand personality",
          "Convert inventory data into a common unit for an impact category (e.g., kg CO2 eq)",
          "Estimate the profit margin",
          "Identify the stakeholders",
        ],
        correctAnswer: 1,
        explanation: "Characterization factors quantify how much a particular flow contributes to an impact category.",
      },
      {
        id: 14,
        question: "An EPD (Environmental Product Declaration) is based on:",
        options: [
          "A marketing survey",
          "A verified LCA study and Product Category Rules (PCR)",
          "A company's annual financial report",
          "A CEO's statement",
        ],
        correctAnswer: 1,
        explanation: "EPDs are Type III environmental labels based on ISO 14025 and founded on LCA results.",
      },
      {
        id: 15,
        question: "What is 'Sensitivity Analysis' in LCA?",
        options: [
          "Assessing how much the results change when inputs or assumptions vary",
          "Protecting confidential data",
          "Evaluating the emotional impact of the study",
          "Checking the accuracy of the weight scale",
        ],
        correctAnswer: 0,
        explanation: "Sensitivity analysis determines how changes in data and choices affect the results of an LCA.",
      },
      {
        id: 16,
        question: "The 'Interpretation' phase of LCA aims to:",
        options: [
          "Translate the study into different languages",
          "Identify significant issues and reach conclusions/recommendations",
          "Calculate the final cost of the product",
          "Create a logo for the product",
        ],
        correctAnswer: 1,
        explanation: "Interpretation is the final phase where results are evaluated in relation to the goal and scope.",
      },
      {
        id: 17,
        question: "Which impact category is measured in kg SO2 equivalent?",
        options: [
          "Global Warming",
          "Acidification",
          "Eutrophication",
          "Ozone Depletion",
        ],
        correctAnswer: 1,
        explanation: "Acidification potential is typically expressed in sulfur dioxide (SO2) equivalents.",
      },
      {
        id: 18,
        question: "What is 'Secondary Data' in LCA?",
        options: [
          "Data that is less important",
          "Generic data from databases or literature used when primary data is unavailable",
          "The second set of measurements taken",
          "Data collected by a secondary school",
        ],
        correctAnswer: 1,
        explanation: "Secondary data refers to data not directly measured from the specific system but pulled from external sources.",
      },
      {
        id: 19,
        question: "Eutrophication potential refers to:",
        options: [
          "The warming of the atmosphere",
          "Excessive enrichment of water with nutrients (Nitrogen/Phosphorus)",
          "The thinning of the ozone layer",
          "The depletion of fossil fuels",
        ],
        correctAnswer: 1,
        explanation: "Eutrophication leads to algal blooms and oxygen depletion in water bodies due to nutrient runoff.",
      },
      {
        id: 20,
        question: "Which of these is a common LCA software tool?",
        options: ["Adobe Photoshop", "SimaPro or GaBi", "Microsoft Excel only", "AutoCAD"],
        correctAnswer: 1,
        explanation: "SimaPro and GaBi are industry-standard professional software tools for conducting LCAs.",
      },
    ],
  },
  "sustainability-fundamentals-esg": {
    title: "Sustainability Fundamentals & ESG",
    emoji: "🌿",
    headerBg: "#1A4A38",
    questions: [
      {
        id: 1,
        question: "The Triple Bottom Line framework consists of:",
        options: ["Economy, Ecology, Ethics", "People, Planet, Profit", "Society, Environment, Governance", "Finance, Operations, Strategy"],
        correctAnswer: 1,
        explanation: "The Triple Bottom Line (TBL) is a sustainability framework that focuses on social (people), environmental (planet), and economic (profit) impacts.",
      },
      {
        id: 2,
        question: "The UN SDGs consist of how many goals?",
        options: ["10", "15", "17", "21"],
        correctAnswer: 2,
        explanation: "The Sustainable Development Goals (SDGs) are a collection of 17 interlinked global goals designed to be a blueprint to achieve a better and more sustainable future for all.",
      },
      {
        id: 3,
        question: "What does ESG stand for?",
        options: ["Environmental, Social, and Governance", "Economic, Sustainable, and Growth", "Environmental, Systemic, and Global", "Efficiency, Stability, and Governance"],
        correctAnswer: 0,
        explanation: "ESG stands for Environmental, Social, and Governance, the three key factors in measuring the sustainability and ethical impact of an investment.",
      },
      {
        id: 4,
        question: "Which reporting framework is primarily used for climate-related financial disclosures?",
        options: ["GRI", "SASB", "TCFD", "SDG Compass"],
        correctAnswer: 2,
        explanation: "The Task Force on Climate-related Financial Disclosures (TCFD) provides a framework for companies to disclose climate-related financial risks.",
      },
      {
        id: 5,
        question: "What is 'Greenwashing'?",
        options: ["Cleaning industrial waste", "Making misleading claims about environmental benefits", "Investing in renewable energy", "Using recycled paper"],
        correctAnswer: 1,
        explanation: "Greenwashing is the process of conveying a false impression or providing misleading information about how a company's products are more environmentally sound.",
      },
      {
        id: 6,
        question: "What does 'Materiality' mean in ESG reporting?",
        options: ["The physical materials used in production", "The financial importance of an ESG issue to a company", "The weight of the sustainability report", "The cost of raw materials"],
        correctAnswer: 1,
        explanation: "Materiality refers to the ESG topics that are most significant to a company's business performance and its stakeholders.",
      },
      {
        id: 7,
        question: "Which of these is a 'Social' factor in ESG?",
        options: ["Carbon emissions", "Board diversity", "Labor practices and human rights", "Executive compensation"],
        correctAnswer: 2,
        explanation: "Labor practices, human rights, and employee health and safety fall under the 'Social' pillar of ESG.",
      },
      {
        id: 8,
        question: "What is the 'Net Zero' target aim?",
        options: ["Zero carbon emissions", "Balancing GHG emitted with GHG removed from the atmosphere", "Using only zero-cost energy", "Zero waste to landfill"],
        correctAnswer: 1,
        explanation: "Net Zero means achieving a balance between the amount of greenhouse gas produced and the amount removed from the atmosphere.",
      },
      {
        id: 9,
        question: "Which standard-setting body recently launched the IFRS Sustainability Disclosure Standards?",
        options: ["GRI", "ISSB", "EFRAG", "SEC"],
        correctAnswer: 1,
        explanation: "The International Sustainability Standards Board (ISSB) was established to create a global baseline for sustainability-related financial disclosures.",
      },
      {
        id: 10,
        question: "What is 'Double Materiality'?",
        options: ["Reporting twice a year", "Considering both financial impact on the company and company impact on society/environment", "Using two different reporting standards", "Reporting on both direct and indirect emissions"],
        correctAnswer: 1,
        explanation: "Double Materiality looks at how sustainability issues affect a company (financial) and how the company affects the world (impact).",
      },
      {
        id: 11,
        question: "Which of these is a 'Governance' factor in ESG?",
        options: ["Waste management", "Community engagement", "Anti-corruption and bribery policies", "Employee training"],
        correctAnswer: 2,
        explanation: "Governance includes a company’s leadership, executive pay, audits, internal controls, and shareholder rights.",
      },
      {
        id: 12,
        question: "What is the 'Circular Economy'?",
        options: ["A business model that only uses coins", "A system aimed at eliminating waste and the continual use of resources", "An economy that grows every year", "Trading goods in a circle"],
        correctAnswer: 1,
        explanation: "A circular economy is based on the principles of designing out waste and pollution, keeping products and materials in use, and regenerating natural systems.",
      },
      {
        id: 13,
        question: "What is the 'S' in CSRD (Corporate Sustainability Reporting Directive)?",
        options: ["Systemic", "Social", "Sustainability", "Standard"],
        correctAnswer: 2,
        explanation: "CSRD is the EU directive that requires companies to report on the impact of their activities on people and the planet.",
      },
      {
        id: 14,
        question: "Which framework focuses on industry-specific ESG standards for investors?",
        options: ["GRI", "SASB", "UN Global Compact", "ISO 26000"],
        correctAnswer: 1,
        explanation: "The Sustainability Accounting Standards Board (SASB) provides industry-specific standards that identify the subset of ESG issues most relevant to financial performance.",
      },
      {
        id: 15,
        question: "What is an 'ESG Rating'?",
        options: ["A score given by customers", "An assessment of a company's resilience to long-term ESG risks", "The interest rate on a green bond", "A government-mandated tax score"],
        correctAnswer: 1,
        explanation: "ESG ratings (from providers like MSCI or Sustainalytics) measure a company’s exposure to long-term ESG risks and how well it manages them.",
      },
      {
        id: 16,
        question: "What are 'Planetary Boundaries'?",
        options: ["The borders between countries", "A framework defining safe operating limits for humanity across 9 Earth systems", "The physical size of the Earth", "The distance from Earth to the moon"],
        correctAnswer: 1,
        explanation: "Planetary Boundaries (from the Stockholm Resilience Centre) identify the environmental limits within which humanity can safely operate.",
      },
      {
        id: 17,
        question: "What is 'Impact Investing'?",
        options: ["Investing only in high-risk stocks", "Investments made to generate positive, measurable social and environmental impact alongside a financial return", "Investing after a market crash", "Using high-impact marketing to sell stocks"],
        correctAnswer: 1,
        explanation: "Impact investing targets specific social or environmental goals in addition to seeking a financial return.",
      },
      {
        id: 18,
        question: "What does the 'G' in GRI stand for?",
        options: ["Governance", "Global", "Green", "Growth"],
        correctAnswer: 1,
        explanation: "GRI stands for the Global Reporting Initiative, the world's most widely used standards for sustainability reporting.",
      },
      {
        id: 19,
        question: "What is a 'Stranded Asset'?",
        options: ["An asset lost at sea", "An asset that has suffered from unanticipated or premature write-downs (e.g., fossil fuel reserves)", "A property in a remote location", "A bank account with no activity"],
        correctAnswer: 1,
        explanation: "Stranded assets are assets that have lost value or turned into liabilities due to the energy transition or environmental regulations.",
      },
      {
        id: 20,
        question: "What is 'Scope 3' in the context of emissions?",
        options: ["Direct emissions from the company", "Indirect emissions from purchased energy", "All other indirect emissions in a company's value chain", "Emissions from the company's 3rd factory"],
        correctAnswer: 2,
        explanation: "Scope 3 includes all indirect emissions that occur in the value chain of the reporting company, including both upstream and downstream emissions.",
      },
    ],
  },
};
